# Generated by Django 4.0.3 on 2022-04-19 08:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(help_text="The user's email address ending in @teachersucenter.com", max_length=254, unique=True)),
                ('ms_id', models.CharField(help_text='The object id of the user object in the Azure Active Directory', max_length=512, unique=True)),
                ('role', models.CharField(default='USR', help_text='The role of the user. There are three roles, namely: SDM, ADM and USR. You can read more in the docs.', max_length=8)),
                ('date_joined', models.DateTimeField(default=datetime.datetime(2022, 4, 19, 8, 26, 21, 164514, tzinfo=utc), help_text='The date the user joined Duwin.')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, help_text='Creation datetime of this object.')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='Last edited datetime of this object.')),
                ('name', models.CharField(help_text="The author's name.", max_length=512)),
                ('cover', models.ImageField(default='author_covers/default.jpg', help_text="The author's cover image.", upload_to='author_covers')),
                ('birth', models.DateField(help_text="The author's date of birth.")),
                ('death', models.DateField(default=None, help_text="The author's date of death. Null if the author is still alive.", null=True)),
                ('description', models.TextField(help_text="The author's description. Saved in md format.")),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, help_text='Creation datetime of this object.')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='Last edited datetime of this object.')),
                ('title', models.CharField(help_text='The title of the book.', max_length=512)),
                ('published_date', models.DateField(help_text='The date of publication of the book. Null if unknown.', null=True)),
                ('short_description', models.CharField(help_text='A short description.', max_length=512)),
                ('long_description', models.TextField(help_text='A longer, more descriptive description. Saved in md format.')),
                ('cover', models.ImageField(default='book_covers/default.jpg', help_text='The cover image of the book.', upload_to='book_covers')),
                ('length', models.IntegerField(default=None, help_text='The page count of the book.', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, help_text='Creation datetime of this object.')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='Last edited datetime of this object.')),
                ('name', models.CharField(help_text='The name of the genre.', max_length=512)),
                ('tagline', models.TextField(help_text='A brief description describing the genre.')),
                ('cover', models.ImageField(default='genre_covers/default.jpg', help_text="The genre's cover image.", upload_to='genre_covers')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, help_text='Creation datetime of this object.')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='Last edited datetime of this object.')),
                ('name', models.CharField(help_text='The name of the link.', max_length=512)),
                ('url', models.URLField(help_text='The url, yea, pretty self-explanatory.', max_length=512)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, help_text='Creation datetime of this object.')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='Last edited datetime of this object.')),
                ('condition', models.CharField(help_text='"read" to add to the user\'s Reading List, and "fav" for their Favourites', max_length=32)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, help_text='Creation datetime of this object.')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='Last edited datetime of this object.')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.book')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.link')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, help_text='Creation datetime of this object.')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='Last edited datetime of this object.')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.book')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.genre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, help_text='Creation datetime of this object.')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='Last edited datetime of this object.')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.book')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
