# Generated by Django 4.0.3 on 2022-03-17 13:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_book_key_book_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(help_text="The author's name.", max_length=512)),
                ('cover', models.ImageField(default='author_covers/default.jpg', help_text="The author's cover image.", upload_to='author_covers')),
                ('birth', models.DateField(help_text="The author's birth date.")),
                ('death', models.DateField(default=None, help_text="The author's date of death. Null if the author is still alive.", null=True)),
                ('description', models.TextField(help_text="The author's description. Saved in md format.")),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(help_text='The name of the genre.', max_length=512)),
                ('tagline', models.TextField(help_text='A brief description describing the genre.')),
                ('colour', models.CharField(help_text='The colour of the genre, stored in hexadecimal.', max_length=7)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='book_covers/default.jpg', help_text='The cover image of the book.', upload_to='book_covers'),
        ),
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='book',
            name='length',
            field=models.IntegerField(default=420, help_text='The paper count of the book.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='published_date',
            field=models.DateField(help_text='The date of publication of the book. Null if unknown', null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 3, 17, 13, 16, 59, 506471, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='long_description',
            field=models.TextField(help_text='A longer, more descriptive description. Saved in md format.'),
        ),
        migrations.AlterField(
            model_name='book',
            name='short_description',
            field=models.CharField(help_text='A short description.', max_length=512),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(help_text='The title of the book.', max_length=512),
        ),
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.book')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
