# Generated by Django 4.0.3 on 2022-03-26 08:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_link_remove_genre_colour_genre_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ms_id',
            field=models.CharField(default=datetime.datetime(2022, 3, 26, 8, 44, 19, 563319, tzinfo=utc), max_length=512, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 26, 8, 44, 16, 358629, tzinfo=utc)),
        ),
    ]
