# Generated by Django 4.0.3 on 2022-03-26 09:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_ms_id_alter_user_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SDM', 'Super-admin'), ('ADM', 'Admin'), ('USR', 'User')], default='USR', max_length=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 26, 9, 8, 30, 998753, tzinfo=utc)),
        ),
    ]
